# Generated by Django 6.0 on 2025-12-16 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('create_date', models.DateField(default='')),
                ('end_date', models.DateField()),
                ('description', models.TextField(max_length=500)),
                ('status', models.CharField(blank=True, choices=[('iniciado', 'Em andamento'), ('em pausa', 'Pausado'), ('finalizado', 'Finalizado')], null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
